name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
    permission:
  contents: read
  pull-requests: write

jobs:
  ai_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run AI Code Reviewer
        uses: ./ai-code-reviewer
        with: 
     _sk-svcacct-har5GKODfk8-tj201s33ZljryjcWD4W7-6H2Ub5yEBSvP8axegYfd69_j3WKhLwYwkQW0VRv0OT3BlbkFJBbshA3_NYfZSR6l77qSgPrj9Crgtr8KZPPoFJrZPTlUSYu1FfM-rKu70ETKAMctd9eu0G8RJgA",
        GITHUB_TOKEN=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
